Testing command

diff --git a/.github/workflows/publish.yaml b/.github/workflows/publish.yaml
--- a/.github/workflows/publish.yaml
+++ b/.github/workflows/publish.yaml
@@ -30,12 +30,18 @@ jobs:
             echo "::error::ERROR: Please pick a correct module from the selection"
             exit 1
 
-        - name: Is Tag
+        - name: Verify TAG Selection
 #          if: env.IS_TAG == 'true'
           run: |
-            echo "tinkar-starter-data-properties-v2.0.0" | awk -F'-v' '{print $1, $2}'
-            part1=$(echo "$TAG" | awk -F'-v' '{print $1}')
-            echo "Part 1: $part1"
+            TAG_MODULE=$(echo "$TAG" | awk -F'-v' '{print $1}')
+            echo "TAG_MODULE: $TAG_MODULE"
+            echo "MODULE_CHOSEN: $MODULE"
+            echo ""
+            if [ "$TAG_MODULE" != "$MODULE" ]; then
+              echo "::error::$TAG Does Not Match $MODULE"
+              echo "::error::Please select correct Module"
+              exit 1
+            fi
             exit 1;
           env:
             TAG: "tinkar-starter-data-properties-v2.0.0"
